"""Check the finished draft against the link check. No model call.

Two failures survived three revisions of the note-5 draft, and both were
caused by instructions added to the drafting prompt. A prompt sentence saying
"do not" lost the argument every time, so these are code:

1. DEAD CITATION. The draft opened on "an ASCI report from August 2026 showed
   39 of 40 ads failed to substantiate claims", citing a page that returns
   404. "Open on the industry hook" pulls the draft towards the most
   newsworthy fact in the research, and that fact's source did not exist.

2. UNSUPPORTED DATE. The draft wrote "Research from August 2026 shows that
   over 68% of urban female consumers..." from a source page dated
   2023-08-01. It did not merely fail to state the age - it asserted a date
   the source does not support. That is fabrication, and it was caused by
   telling the drafter to make recency visible in the opening.

Both are decidable by comparing the draft's own SOURCES table against the
link check, which is a measurement. Neither needs a model, and neither can be
argued with.
"""

import re

MONTHS = ("january february march april may june july august september "
          "october november december").split()
_MONTH_YEAR = re.compile(r"\b(" + "|".join(MONTHS) + r")\s+(20\d{2})\b", re.I)
_URL = re.compile(r"https?://[^\s<>\"'\)\]\|]+")


def parse_link_report(markdown):
    """Rows back out of 02a-link-check.md: [{url, code, state, date}].

    The report is generated by links.report(), so this is reading our own
    output - but reading it rather than passing objects around means a draft
    can be re-checked later from the files on disk alone."""
    rows = []
    for line in (markdown or "").splitlines():
        if not line.startswith("|") or "http" not in line:
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 4 or not cells[0].startswith("http"):
            continue
        rows.append({"url": cells[0].rstrip("."), "code": cells[1],
                     "state": cells[2].upper(),
                     "date": "" if cells[3] == "-" else cells[3]})
    return rows


def _bad(rows):
    """URLs a draft may not stand on: the page does not exist, or it is not a
    readable page (an image or a PDF opening proves the file is there, not
    that a claim can be read off it)."""
    out = {}
    for r in rows:
        if r["state"] == "DEAD":
            out[r["url"]] = f"DEAD ({r['code']}) - the page does not exist"
    return out


def dead_citations(sources_table, link_rows):
    """[(url, why)] for every source the draft cites that is dead."""
    bad = _bad(link_rows)
    cited = []
    seen = set()
    for url in _URL.findall(sources_table or ""):
        url = url.rstrip(".,;:)")
        if url in seen:
            continue
        seen.add(url)
        if url in bad:
            cited.append((url, bad[url]))
    return cited


def source_months(link_rows):
    """{(month, year)} that the fetched pages actually carry."""
    out = set()
    for r in link_rows:
        m = re.match(r"(20\d{2})-(\d{2})", r["date"] or "")
        if m:
            out.add((int(m.group(2)), int(m.group(1))))
    return out


def unsupported_dates(post, link_rows):
    """[(phrase, why)] for a month and year asserted in the post that no
    fetched source carries.

    Only month+year is checked. A bare year is often a projection - "$590
    billion by 2030" is a forecast, not a claim about when something was
    published - and flagging those would bury the real thing."""
    have = source_months(link_rows)
    if not have:
        # Nothing was fetched with a date, so every asserted date is unbacked.
        have = set()
    out, seen = [], set()
    for m in _MONTH_YEAR.finditer(post or ""):
        phrase = m.group(0)
        key = phrase.lower()
        if key in seen:
            continue
        seen.add(key)
        month = MONTHS.index(m.group(1).lower()) + 1
        year = int(m.group(2))
        if (month, year) not in have:
            dates = ", ".join(f"{y}-{mo:02d}" for mo, y in sorted(have, key=lambda p: (p[1], p[0]))) or "none"
            out.append((phrase, f"no fetched source is dated {phrase} "
                                f"(the pages carry: {dates})"))
    return out


def report(post, sources_table, link_report_md):
    """A blocker list the voice checker is handed as fact, and the bot puts at
    the top of the message. DO NOT POST is not a judgement about quality."""
    rows = parse_link_report(link_report_md)
    dead = dead_citations(sources_table, rows)
    dates = unsupported_dates(post, rows)

    lines = ["# Citation check (mechanical, no model call)", ""]
    if not rows:
        lines += ["No link check was available, so nothing could be checked.", ""]
    lines.append("## Sources cited that do not exist")
    lines += ([f"- {url} - {why}" for url, why in dead] or ["None."])
    lines += ["", "## Dates asserted that no source supports"]
    lines += ([f"- \"{phrase}\" - {why}" for phrase, why in dates] or ["None."])
    lines += ["", f"BLOCKERS: {len(dead) + len(dates)}"]
    if dead or dates:
        lines.append("DO NOT POST until these are fixed. A dead citation and a "
                     "date the source does not carry are both fabrication, "
                     "whatever else is right about the draft.")
    return "\n".join(lines) + "\n", dead, dates
